# Generated by Django 5.0 on 2024-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEOptionBrew', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alpaca_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
